### ISSUE TITLE
Navgraph is broken

### ISSUE THREAD

**Issue by QuicheLorraine3600** [Chimpagne/ChimpagneApp#118]
Back button doesn't work well (always go back to the same screen)

**Comment by Athanaze** [comment]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/4e1c0ed1-5c21-4aaf-8811-42c7dfa1e4d3)
The kind of issues I am having with the tests might actually be a related probem..

This solution proposed by Claude 3 Opus involves doing this:

 navController.setGraph(R.navigation.your_navigation_graph) // Replace with your actual navigation graph resource


But we don't have a graph resource AFAIK
