### ISSUE TITLE
Inconsistent use of shadows in the UI

### ISSUE THREAD

**Issue by Athanaze** [Chimpagne/ChimpagneApp#191]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/f6ab57b5-5151-4054-81d0-0150993fbbf2)

**Comment by QuicheLorraine3600** [comment]
What do you suggest ? Adding more shadows or remove all of them ? I personally prefer the first option.

**Comment by leagrieder** [comment]
This has been resolved
