### ISSUE TITLE
Should we force public events to have a location and a description ?

### ISSUE THREAD

**Issue by Athanaze** [Chimpagne/ChimpagneApp#194]

**Comment by QuicheLorraine3600** [comment]
A public event without location cannot be found on the map. The goal of the app isn't to have "online" events so I don't see why there could be an event without location. However, I don't see why a description should be required.

**Comment by juaniac** [comment]
I believe events should have a title, location, date and time. 
All other fields are optional.

**Comment by Athanaze** [comment]
I don't see why we should reject online events personally.
Including a zoom link could be useful.

**Comment by juaniac** [comment]
Because the focus of the app is to organize events and find in person events near you.

**Comment by QuicheLorraine3600** [comment]
> I don't see why we should reject online events personally. Including a zoom link could be useful.

Yeah but how do you discover online events ? By definition, they don't appear on the map :(
What can Chimpagne bring to online users ? Supplies, parking, beds become useless. I personally never used on my phone.

**Comment by Athanaze** [comment]
why is there a discord link then ?
Chimpagne brings reminders, discovery via the feed & staff management.
In my opinion, for private events, forcing to set the location adds too much friction to an already cumbersome process.

**Comment by juaniac** [comment]
I believe the discord link is the link for the general chat, to have more options than telegram and WhatsApp.

**Comment by Athanaze** [comment]
The decision has been made for public events:
- The location will be mandatory
- The description will stay optional
