### ISSUE TITLE
Not filter used by the feed

### ISSUE THREAD

**Issue by QuicheLorraine3600** [Chimpagne/ChimpagneApp#198]
Here is the code used by the feed to fetch events.
![image](https://github.com/Chimpagne/ChimpagneApp/assets/39198541/2d8da876-8b3e-419a-a36f-e3e7bbf20ea8)

As you can see NO FILTERS ARE USED. Thus, this returns privates events, events in the past and events I already joined, making the feed completely unusable.

**Comment by QuicheLorraine3600** [comment]
+really ugly magic value

**Comment by Athanaze** [comment]
My improvement plan for the feed (PR coming soon ™):

100km as a reasonable value for the search radius. Events further than that won't be shown.

As discussed, the filters will block the following events:
- Private events
- Past events
- Events I already joined

When the GPS is not turned on, a gray text will be displayed:
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/c5cb52ed-e95c-466e-9bf8-38a383a83239)

**Comment by juaniac** [comment]
Good enough of a change,
I believe adding a button or making the "turn on your gps" part of the text clickable (and of the color blue) to have the "do you want to enable your gps" pop up to re-appear would be a nice change to add.

**Comment by QuicheLorraine3600** [comment]
Yep cf issue #201
