### ISSUE TITLE
The CI makes us wildly unproductive, running it four times is not a solution

### ISSUE THREAD

**Issue by Athanaze** [Chimpagne/ChimpagneApp#199]
Here are some tests that did not pass on the first try, but passed after retrying a few time (my personal record is launching the CI four times, without changing anything, until the test passed)

![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/f700069e-331b-44c2-afa1-0bdf1075ddbc)

![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/11656756-9865-4406-a4dd-221dfa7d7fb2)

![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/d9fdc7d4-77b9-4386-8720-6616d2bcf099)

![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/70d1f038-3367-4906-8d1c-2bd8242f8f31)

![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/d25d45b7-dff9-4682-a2f4-65e7965e27e7)

**Comment by Athanaze** [comment]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/da0d537c-dc2e-4591-8de7-40a4febe737c)

**Comment by QuicheLorraine3600** [comment]
Those issues happens when multiple instances of the CI are launched at the same time. The solution is just to be sure only one is running at a time. So you have to be kind and cancel your CI when another is already launched.

**Comment by Athanaze** [comment]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/1d36b2c8-ed93-40e3-aeac-e81e103bd2b3)

**Comment by Athanaze** [comment]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/fc8c5446-31c5-4217-a7e0-1ef7279b6782)

**Comment by Athanaze** [comment]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/29517376/4a283642-b243-4d6b-9b3b-38caebe35986)
