### ISSUE TITLE
The events near you feed should not appear when location is disabled

### ISSUE THREAD

**Issue by juaniac** [Chimpagne/ChimpagneApp#201]
Here is a photo of the ugly result:
<img width="175" alt="image" src="https://github.com/Chimpagne/ChimpagneApp/assets/125994939/fa9f01b3-2628-4a6e-87cd-5db17f25ed8a">
Also as a side note, this should also be the case if there are not events near you.

**Comment by QuicheLorraine3600** [comment]
Another solution would be to add a text:
![image](https://github.com/Chimpagne/ChimpagneApp/assets/39198541/20100c1d-ecf6-461f-9bcc-2ab35da9d0b2)

**Comment by juaniac** [comment]
Yes, the biggest issue is the abnormal gap between the title and the navigation buttons.
