### ISSUE TITLE
Unclear share button

### ISSUE THREAD

**Issue by QuicheLorraine3600** [Chimpagne/ChimpagneApp#205]
![image](https://github.com/Chimpagne/ChimpagneApp/assets/39198541/59ca5c92-bdf9-40b7-8433-7efd901d33d1)
On my device, nothing tells me that the event link has been copied to my clipboard

**Comment by QuicheLorraine3600** [comment]
Suggestion from @juaniac: add a toast

**Comment by juaniac** [comment]
we should also replace the icon by the clipboard icon so that it is clear that we are copying a link.

**Comment by QuicheLorraine3600** [comment]
Or use this https://developer.android.com/training/sharing/send
